---
- name: cp docker proxy 
  hosts: all
  gather_facts: false
  tasks:
    - name: remove docker proxy file
      shell: /bin/rm -rf  /etc/systemd/system/docker.service.d/*

    - name: cp docker proxy file
      copy:
        src="/etc/systemd/system/docker.service.d/http_proxy.conf"
        dest="/etc/systemd/system/docker.service.d/"

    - name: Restart docker
      shell: |
        systemctl daemon-reload
        systemctl restart docker
   
