apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ClusterImagePolicy
metadata:
  name: ibmcloud-default-policy
spec:
   repositories:
    # This enforces that all images deployed to this cluster pass trust and VA
    # To override, set an ImagePolicy for a specific Kubernetes namespace or modify this policy
    - name: "registry*.bluemix.net/*"
      policy:
    - name: "docker.io/*"
      policy:
    - name: "mycluster.icp:8500/*"
      policy:
    - name: "ligc.sl.cloud9.ibm.com/library/*"
      policy:
    - name: "registry.ibm.com/library/*"
      policy:
